Resources:
  MyLambda:
    Type: AWS::Lambda::Function
    Metadata:
      Comment:
        ZipFile: |
          print("Hello World!")
    Properties:
      Code:
        ZipFile: |
          print("Hello World!")
      FunctionName: my-lambda
      Handler: index.lambda_handler
      Role: !ImportValue MyLambdaRoleArn
      Runtime: python3.8
      Tags:
        - Key: foo
          Value: myval
        - Key: bar
          Value: myval
