Resources:
  MyLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: "print(\"Hello World!\")\n"
      FunctionName: my-lambda
      Handler: index.lambda_handler
      Role:
        Fn::ImportValue: MyLambdaRoleArn
      Runtime: python3.8
      Tags:
      - Key: foo
        Value: myval
      - Key: bar
        Value: myval
      - Key: baz
        Value:
          ZipFile: "print(\"Hello World!\")\n"
