Parameters:
  ParentVal:
    Type: String
  AppName:
    Type: String
Resources:
  MySubBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mod-in-mod-bucket
      XName: !Sub ${ParentVal}-abc
      YName: !Sub ${AppName}-xyz
