Parameters:
  Name:
    Type: String
  B:
    Type: Boolean
Resources:
  Bucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref Name
      Parent:
        - Child:
            ShouldBeFalse: !Ref B
        - OtherChild: !Ref B
        - Subs:
          - !Sub "b0${B}"
          - !Sub "b1${B}"
  Bucket2:
    Type: AWS::S3::Bucket

