Resources:
  MyBucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: foo
      X: !Sub ${Foo}
      Y:
        - !Sub noparent0-${Foo}
        - !Sub noparent1-${Foo}
  MyBucket2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bar
