Parameters:
    queueName: testQueue
Tags:
    stackset: testStackSet
stackset:
    stacksetname: test
    administrationrolearn: null
    autodeployment: null
    callas: ""
    capabilities:
        - CAPABILITY_NAMED_IAM
        - CAPABILITY_AUTO_EXPAND
    description: test description
    executionrolename: null
    managedexecution: null
    parameters: []
    permissionmodel: ""
    stackid: null
    tags: []
stacksetinstanses:
    regions:
        - us-east-1
        - us-east-2
    stacksetname: null
    accounts:
        - "577613639135"
    callas: ""
    deploymenttargets: null
    operationpreferences: null