
on:
  push:
    tags:
    - 'pkl*'

name: Create Pkl package release from tag

jobs:
  pkl:
    name: Pkl
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          set -x
          curl -L -o /tmp/pkl https://github.com/apple/pkl/releases/download/0.25.2/pkl-linux-amd64
          chmod +x /tmp/pkl
          /tmp/pkl --version
          /tmp/pkl project package pkl
          gh release upload "${GITHUB_REF##*/}" .out/cloudformation@0.1.0/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

